sudo: required
language: generic

services:
- docker

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

arch:
        packages:
        - go
        script:
        - "set -e"
        - "make test"
        - "./tests/install_aurweb-test.sh"
        - "systemctl start aurweb-test"
        - "./tests/test_connection.sh"

