sudo: required

services:
- docker

arch:
        packages:
        - go
        script:
        - make test
        - "./init/aur.sh"
        - "ls -lh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
