sudo: required
language: generic

services:
- docker

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

arch:
        packages:
        - go
        script:
        - make test
        - "./tests/init/aur.sh"
        - "ls -lh"

