sudo: required

services:
- docker

arch:
  packages:
  # pacman packages
  - go
  script:
  - "./init/aur.sh"
  - "ls -lh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
